---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-publishing-kindlegen",
         tags: ["create", "update"]
       }

  tasks:

    - debug: msg="Tasks section"



